/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Analytics Service API
 * Analytics Service API
 * OpenAPI spec version: 1.0
 */
import { customAxios } from '../../axiosInstance';

import type { AnalyticsSummaryResponse } from '../../models';

export const getAnalytics = () => {
  /**
   * Возвращает общее число подписок, сумму, разбивку по категориям и ближайшие списания
   * @summary Получить сводную аналитику по подпискам
   */
  const getSummary = () => {
    return customAxios<AnalyticsSummaryResponse>({ url: `/api/analytics/summary`, method: 'GET' });
  };
  return { getSummary };
};
export type GetSummaryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAnalytics>['getSummary']>>
>;
