/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Analytics Service API
 * Analytics Service API
 * OpenAPI spec version: 1.0
 */
import { useInfiniteQuery, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type { AnalyticsSummaryResponse, BaseExceptionMessage } from '../../models';

import { customAxios } from '../../axiosInstance';

/**
 * Возвращает общее число подписок, сумму, разбивку по категориям и ближайшие списания
 * @summary Получить сводную аналитику по подпискам
 */
export const getSummary = (signal?: AbortSignal) => {
  return customAxios<AnalyticsSummaryResponse>({
    url: `/api/analytics/summary`,
    method: 'GET',
    signal,
  });
};

export const getGetSummaryInfiniteQueryKey = () => {
  return ['infinate', `/api/analytics/summary`] as const;
};

export const getGetSummaryQueryKey = () => {
  return [`/api/analytics/summary`] as const;
};

export const getGetSummaryInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getSummary>>>,
  TError = BaseExceptionMessage,
>(options?: {
  query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSummaryInfiniteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSummary>>> = ({ signal }) =>
    getSummary(signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSummaryInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getSummary>>>;
export type GetSummaryInfiniteQueryError = BaseExceptionMessage;

export function useGetSummaryInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSummary>>>,
  TError = BaseExceptionMessage,
>(
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSummary>>,
          TError,
          Awaited<ReturnType<typeof getSummary>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSummaryInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSummary>>>,
  TError = BaseExceptionMessage,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSummary>>,
          TError,
          Awaited<ReturnType<typeof getSummary>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSummaryInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSummary>>>,
  TError = BaseExceptionMessage,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить сводную аналитику по подпискам
 */

export function useGetSummaryInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSummary>>>,
  TError = BaseExceptionMessage,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSummaryInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getSummary>>,
  TError = BaseExceptionMessage,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSummaryQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSummary>>> = ({ signal }) =>
    getSummary(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getSummary>>>;
export type GetSummaryQueryError = BaseExceptionMessage;

export function useGetSummary<
  TData = Awaited<ReturnType<typeof getSummary>>,
  TError = BaseExceptionMessage,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSummary>>,
          TError,
          Awaited<ReturnType<typeof getSummary>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSummary<
  TData = Awaited<ReturnType<typeof getSummary>>,
  TError = BaseExceptionMessage,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSummary>>,
          TError,
          Awaited<ReturnType<typeof getSummary>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSummary<
  TData = Awaited<ReturnType<typeof getSummary>>,
  TError = BaseExceptionMessage,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить сводную аналитику по подпискам
 */

export function useGetSummary<
  TData = Awaited<ReturnType<typeof getSummary>>,
  TError = BaseExceptionMessage,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSummaryQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetSummarySuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getSummary>>,
  TError = BaseExceptionMessage,
>(options?: {
  query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSummaryQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSummary>>> = ({ signal }) =>
    getSummary(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSummarySuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getSummary>>>;
export type GetSummarySuspenseQueryError = BaseExceptionMessage;

export function useGetSummarySuspense<
  TData = Awaited<ReturnType<typeof getSummary>>,
  TError = BaseExceptionMessage,
>(
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSummarySuspense<
  TData = Awaited<ReturnType<typeof getSummary>>,
  TError = BaseExceptionMessage,
>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSummarySuspense<
  TData = Awaited<ReturnType<typeof getSummary>>,
  TError = BaseExceptionMessage,
>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить сводную аналитику по подпискам
 */

export function useGetSummarySuspense<
  TData = Awaited<ReturnType<typeof getSummary>>,
  TError = BaseExceptionMessage,
>(
  options?: {
    query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSummary>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSummarySuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
