/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */
import { useInfiniteQuery, useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type {
  BaseExceptionMessage,
  CategoryResponse,
  CreateSubscriptionRequest,
  CustomSubscriptionRequest,
  GetServicesParams,
  GetSubscriptionsParams,
  PageServiceResponse,
  PageSubscriptionResponse,
  SubscriptionResponse,
  UpdateSubscriptionRequest,
  UploadCustomLogoBody,
} from '../../models';

import { customAxios } from '../../axiosInstance';

/**
 * @summary Получить подписку по ID
 */
export const getSubscriptionById = (subscriptionId: string, signal?: AbortSignal) => {
  return customAxios<SubscriptionResponse>({
    url: `/api/subscription/${subscriptionId}`,
    method: 'GET',
    signal,
  });
};

export const getGetSubscriptionByIdInfiniteQueryKey = (subscriptionId?: string) => {
  return ['infinate', `/api/subscription/${subscriptionId}`] as const;
};

export const getGetSubscriptionByIdQueryKey = (subscriptionId?: string) => {
  return [`/api/subscription/${subscriptionId}`] as const;
};

export const getGetSubscriptionByIdInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptionById>>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSubscriptionByIdInfiniteQueryKey(subscriptionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSubscriptionById>>> = ({ signal }) =>
    getSubscriptionById(subscriptionId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!subscriptionId,
    ...queryOptions,
  } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetSubscriptionByIdInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSubscriptionById>>
>;
export type GetSubscriptionByIdInfiniteQueryError =
  | SubscriptionResponse
  | BaseExceptionMessage
  | BaseExceptionMessage;

export function useGetSubscriptionByIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptionById>>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptionById>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptionById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSubscriptionByIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptionById>>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptionById>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptionById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSubscriptionByIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptionById>>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить подписку по ID
 */

export function useGetSubscriptionByIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptionById>>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSubscriptionByIdInfiniteQueryOptions(subscriptionId, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetSubscriptionByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getSubscriptionById>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSubscriptionByIdQueryKey(subscriptionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSubscriptionById>>> = ({ signal }) =>
    getSubscriptionById(subscriptionId, signal);

  return { queryKey, queryFn, enabled: !!subscriptionId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSubscriptionById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSubscriptionByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSubscriptionById>>
>;
export type GetSubscriptionByIdQueryError =
  | SubscriptionResponse
  | BaseExceptionMessage
  | BaseExceptionMessage;

export function useGetSubscriptionById<
  TData = Awaited<ReturnType<typeof getSubscriptionById>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptionById>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptionById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSubscriptionById<
  TData = Awaited<ReturnType<typeof getSubscriptionById>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptionById>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptionById>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSubscriptionById<
  TData = Awaited<ReturnType<typeof getSubscriptionById>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить подписку по ID
 */

export function useGetSubscriptionById<
  TData = Awaited<ReturnType<typeof getSubscriptionById>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSubscriptionByIdQueryOptions(subscriptionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetSubscriptionByIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getSubscriptionById>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSubscriptionByIdQueryKey(subscriptionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSubscriptionById>>> = ({ signal }) =>
    getSubscriptionById(subscriptionId, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getSubscriptionById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSubscriptionByIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSubscriptionById>>
>;
export type GetSubscriptionByIdSuspenseQueryError =
  | SubscriptionResponse
  | BaseExceptionMessage
  | BaseExceptionMessage;

export function useGetSubscriptionByIdSuspense<
  TData = Awaited<ReturnType<typeof getSubscriptionById>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSubscriptionByIdSuspense<
  TData = Awaited<ReturnType<typeof getSubscriptionById>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSubscriptionByIdSuspense<
  TData = Awaited<ReturnType<typeof getSubscriptionById>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить подписку по ID
 */

export function useGetSubscriptionByIdSuspense<
  TData = Awaited<ReturnType<typeof getSubscriptionById>>,
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
>(
  subscriptionId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSubscriptionById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSubscriptionByIdSuspenseQueryOptions(subscriptionId, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Обновить существующую подписку
 */
export const updateSubscription = (
  subscriptionId: string,
  updateSubscriptionRequest: UpdateSubscriptionRequest,
) => {
  return customAxios<SubscriptionResponse>({
    url: `/api/subscription/${subscriptionId}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateSubscriptionRequest,
  });
};

export const getUpdateSubscriptionMutationOptions = <
  TError =
    | SubscriptionResponse
    | BaseExceptionMessage
    | BaseExceptionMessage
    | BaseExceptionMessage,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSubscription>>,
    TError,
    { subscriptionId: string; data: UpdateSubscriptionRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSubscription>>,
  TError,
  { subscriptionId: string; data: UpdateSubscriptionRequest },
  TContext
> => {
  const mutationKey = ['updateSubscription'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSubscription>>,
    { subscriptionId: string; data: UpdateSubscriptionRequest }
  > = (props) => {
    const { subscriptionId, data } = props ?? {};

    return updateSubscription(subscriptionId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateSubscriptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateSubscription>>
>;
export type UpdateSubscriptionMutationBody = UpdateSubscriptionRequest;
export type UpdateSubscriptionMutationError =
  | SubscriptionResponse
  | BaseExceptionMessage
  | BaseExceptionMessage
  | BaseExceptionMessage;

/**
 * @summary Обновить существующую подписку
 */
export const useUpdateSubscription = <
  TError =
    | SubscriptionResponse
    | BaseExceptionMessage
    | BaseExceptionMessage
    | BaseExceptionMessage,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateSubscription>>,
      TError,
      { subscriptionId: string; data: UpdateSubscriptionRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateSubscription>>,
  TError,
  { subscriptionId: string; data: UpdateSubscriptionRequest },
  TContext
> => {
  const mutationOptions = getUpdateSubscriptionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Удалить подписку
 */
export const deleteSubscription = (subscriptionId: string) => {
  return customAxios<void>({ url: `/api/subscription/${subscriptionId}`, method: 'DELETE' });
};

export const getDeleteSubscriptionMutationOptions = <
  TError = void | BaseExceptionMessage | BaseExceptionMessage | BaseExceptionMessage,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSubscription>>,
    TError,
    { subscriptionId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSubscription>>,
  TError,
  { subscriptionId: string },
  TContext
> => {
  const mutationKey = ['deleteSubscription'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteSubscription>>,
    { subscriptionId: string }
  > = (props) => {
    const { subscriptionId } = props ?? {};

    return deleteSubscription(subscriptionId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteSubscriptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteSubscription>>
>;

export type DeleteSubscriptionMutationError =
  | void
  | BaseExceptionMessage
  | BaseExceptionMessage
  | BaseExceptionMessage;

/**
 * @summary Удалить подписку
 */
export const useDeleteSubscription = <
  TError = void | BaseExceptionMessage | BaseExceptionMessage | BaseExceptionMessage,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteSubscription>>,
      TError,
      { subscriptionId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteSubscription>>,
  TError,
  { subscriptionId: string },
  TContext
> => {
  const mutationOptions = getDeleteSubscriptionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Возвращает список всех подписок пользователя
 * @summary Получить все подписки пользователя
 */
export const getSubscriptions = (params: GetSubscriptionsParams, signal?: AbortSignal) => {
  return customAxios<PageSubscriptionResponse>({
    url: `/api/subscription`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetSubscriptionsInfiniteQueryKey = (params?: GetSubscriptionsParams) => {
  return ['infinate', `/api/subscription`, ...(params ? [params] : [])] as const;
};

export const getGetSubscriptionsQueryKey = (params?: GetSubscriptionsParams) => {
  return [`/api/subscription`, ...(params ? [params] : [])] as const;
};

export const getGetSubscriptionsInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptions>>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSubscriptionsInfiniteQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSubscriptions>>> = ({ signal }) =>
    getSubscriptions(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getSubscriptions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSubscriptionsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSubscriptions>>
>;
export type GetSubscriptionsInfiniteQueryError = BaseExceptionMessage;

export function useGetSubscriptionsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptions>>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptions>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSubscriptionsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptions>>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptions>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSubscriptionsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptions>>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить все подписки пользователя
 */

export function useGetSubscriptionsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSubscriptions>>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSubscriptionsInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetSubscriptionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSubscriptions>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSubscriptionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSubscriptions>>> = ({ signal }) =>
    getSubscriptions(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSubscriptions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSubscriptionsQueryResult = NonNullable<Awaited<ReturnType<typeof getSubscriptions>>>;
export type GetSubscriptionsQueryError = BaseExceptionMessage;

export function useGetSubscriptions<
  TData = Awaited<ReturnType<typeof getSubscriptions>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptions>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSubscriptions<
  TData = Awaited<ReturnType<typeof getSubscriptions>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof getSubscriptions>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSubscriptions<
  TData = Awaited<ReturnType<typeof getSubscriptions>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить все подписки пользователя
 */

export function useGetSubscriptions<
  TData = Awaited<ReturnType<typeof getSubscriptions>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSubscriptionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetSubscriptionsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getSubscriptions>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSubscriptionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSubscriptions>>> = ({ signal }) =>
    getSubscriptions(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getSubscriptions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSubscriptionsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSubscriptions>>
>;
export type GetSubscriptionsSuspenseQueryError = BaseExceptionMessage;

export function useGetSubscriptionsSuspense<
  TData = Awaited<ReturnType<typeof getSubscriptions>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSubscriptionsSuspense<
  TData = Awaited<ReturnType<typeof getSubscriptions>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSubscriptionsSuspense<
  TData = Awaited<ReturnType<typeof getSubscriptions>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить все подписки пользователя
 */

export function useGetSubscriptionsSuspense<
  TData = Awaited<ReturnType<typeof getSubscriptions>>,
  TError = BaseExceptionMessage,
>(
  params: GetSubscriptionsParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getSubscriptions>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSubscriptionsSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Создать подписку на существующий сервис
 */
export const createSubscription = (
  createSubscriptionRequest: CreateSubscriptionRequest,
  signal?: AbortSignal,
) => {
  return customAxios<SubscriptionResponse>({
    url: `/api/subscription`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createSubscriptionRequest,
    signal,
  });
};

export const getCreateSubscriptionMutationOptions = <
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSubscription>>,
    TError,
    { data: CreateSubscriptionRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSubscription>>,
  TError,
  { data: CreateSubscriptionRequest },
  TContext
> => {
  const mutationKey = ['createSubscription'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSubscription>>,
    { data: CreateSubscriptionRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createSubscription(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSubscriptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createSubscription>>
>;
export type CreateSubscriptionMutationBody = CreateSubscriptionRequest;
export type CreateSubscriptionMutationError =
  | SubscriptionResponse
  | BaseExceptionMessage
  | BaseExceptionMessage;

/**
 * @summary Создать подписку на существующий сервис
 */
export const useCreateSubscription = <
  TError = SubscriptionResponse | BaseExceptionMessage | BaseExceptionMessage,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSubscription>>,
      TError,
      { data: CreateSubscriptionRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createSubscription>>,
  TError,
  { data: CreateSubscriptionRequest },
  TContext
> => {
  const mutationOptions = getCreateSubscriptionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Создаёт новый сервис и подписку. Для загрузки лого используй POST /custom/{subscriptionId}/logo
 * @summary Создать кастомную подписку
 */
export const createCustomSubscription = (
  customSubscriptionRequest: CustomSubscriptionRequest,
  signal?: AbortSignal,
) => {
  return customAxios<SubscriptionResponse>({
    url: `/api/subscription/custom`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: customSubscriptionRequest,
    signal,
  });
};

export const getCreateCustomSubscriptionMutationOptions = <
  TError = SubscriptionResponse | BaseExceptionMessage,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCustomSubscription>>,
    TError,
    { data: CustomSubscriptionRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCustomSubscription>>,
  TError,
  { data: CustomSubscriptionRequest },
  TContext
> => {
  const mutationKey = ['createCustomSubscription'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCustomSubscription>>,
    { data: CustomSubscriptionRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createCustomSubscription(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCustomSubscriptionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCustomSubscription>>
>;
export type CreateCustomSubscriptionMutationBody = CustomSubscriptionRequest;
export type CreateCustomSubscriptionMutationError = SubscriptionResponse | BaseExceptionMessage;

/**
 * @summary Создать кастомную подписку
 */
export const useCreateCustomSubscription = <
  TError = SubscriptionResponse | BaseExceptionMessage,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCustomSubscription>>,
      TError,
      { data: CustomSubscriptionRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCustomSubscription>>,
  TError,
  { data: CustomSubscriptionRequest },
  TContext
> => {
  const mutationOptions = getCreateCustomSubscriptionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Загрузить логотип кастомной подписки
 */
export const uploadCustomLogo = (
  subscriptionId: string,
  uploadCustomLogoBody: UploadCustomLogoBody,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`logo`, uploadCustomLogoBody.logo);

  return customAxios<SubscriptionResponse>({
    url: `/api/subscription/custom/${subscriptionId}/logo`,
    method: 'POST',
    headers: { 'Content-Type': 'multipart/form-data' },
    data: formData,
    signal,
  });
};

export const getUploadCustomLogoMutationOptions = <
  TError = SubscriptionResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadCustomLogo>>,
    TError,
    { subscriptionId: string; data: UploadCustomLogoBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadCustomLogo>>,
  TError,
  { subscriptionId: string; data: UploadCustomLogoBody },
  TContext
> => {
  const mutationKey = ['uploadCustomLogo'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadCustomLogo>>,
    { subscriptionId: string; data: UploadCustomLogoBody }
  > = (props) => {
    const { subscriptionId, data } = props ?? {};

    return uploadCustomLogo(subscriptionId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadCustomLogoMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadCustomLogo>>
>;
export type UploadCustomLogoMutationBody = UploadCustomLogoBody;
export type UploadCustomLogoMutationError = SubscriptionResponse;

/**
 * @summary Загрузить логотип кастомной подписки
 */
export const useUploadCustomLogo = <TError = SubscriptionResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadCustomLogo>>,
      TError,
      { subscriptionId: string; data: UploadCustomLogoBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof uploadCustomLogo>>,
  TError,
  { subscriptionId: string; data: UploadCustomLogoBody },
  TContext
> => {
  const mutationOptions = getUploadCustomLogoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Возвращает список сервисов с пагинацией, фильтром по категории и поиском по имени
 * @summary Поиск сервисов
 */
export const getServices = (params: GetServicesParams, signal?: AbortSignal) => {
  return customAxios<PageServiceResponse>({
    url: `/api/subscription/service`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetServicesInfiniteQueryKey = (params?: GetServicesParams) => {
  return ['infinate', `/api/subscription/service`, ...(params ? [params] : [])] as const;
};

export const getGetServicesQueryKey = (params?: GetServicesParams) => {
  return [`/api/subscription/service`, ...(params ? [params] : [])] as const;
};

export const getGetServicesInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getServices>>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetServicesInfiniteQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getServices>>> = ({ signal }) =>
    getServices(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getServices>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetServicesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getServices>>>;
export type GetServicesInfiniteQueryError = BaseExceptionMessage;

export function useGetServicesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getServices>>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServices>>,
          TError,
          Awaited<ReturnType<typeof getServices>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetServicesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getServices>>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServices>>,
          TError,
          Awaited<ReturnType<typeof getServices>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetServicesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getServices>>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Поиск сервисов
 */

export function useGetServicesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getServices>>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetServicesInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetServicesQueryOptions = <
  TData = Awaited<ReturnType<typeof getServices>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetServicesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getServices>>> = ({ signal }) =>
    getServices(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getServices>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetServicesQueryResult = NonNullable<Awaited<ReturnType<typeof getServices>>>;
export type GetServicesQueryError = BaseExceptionMessage;

export function useGetServices<
  TData = Awaited<ReturnType<typeof getServices>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServices>>,
          TError,
          Awaited<ReturnType<typeof getServices>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetServices<
  TData = Awaited<ReturnType<typeof getServices>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getServices>>,
          TError,
          Awaited<ReturnType<typeof getServices>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetServices<
  TData = Awaited<ReturnType<typeof getServices>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Поиск сервисов
 */

export function useGetServices<
  TData = Awaited<ReturnType<typeof getServices>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetServicesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetServicesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getServices>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetServicesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getServices>>> = ({ signal }) =>
    getServices(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getServices>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetServicesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getServices>>>;
export type GetServicesSuspenseQueryError = BaseExceptionMessage;

export function useGetServicesSuspense<
  TData = Awaited<ReturnType<typeof getServices>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options: {
    query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetServicesSuspense<
  TData = Awaited<ReturnType<typeof getServices>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetServicesSuspense<
  TData = Awaited<ReturnType<typeof getServices>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Поиск сервисов
 */

export function useGetServicesSuspense<
  TData = Awaited<ReturnType<typeof getServices>>,
  TError = BaseExceptionMessage,
>(
  params: GetServicesParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getServices>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetServicesSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Возвращает список категорий, чтобы выбрать одну из для подписки
 * @summary Получить все категории
 */
export const getCategories = (signal?: AbortSignal) => {
  return customAxios<CategoryResponse[]>({
    url: `/api/subscription/category`,
    method: 'GET',
    signal,
  });
};

export const getGetCategoriesInfiniteQueryKey = () => {
  return ['infinate', `/api/subscription/category`] as const;
};

export const getGetCategoriesQueryKey = () => {
  return [`/api/subscription/category`] as const;
};

export const getGetCategoriesInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getCategories>>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCategoriesInfiniteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCategories>>> = ({ signal }) =>
    getCategories(signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCategoriesInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCategories>>
>;
export type GetCategoriesInfiniteQueryError = unknown;

export function useGetCategoriesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getCategories>>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategories>>,
          TError,
          Awaited<ReturnType<typeof getCategories>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCategoriesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getCategories>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategories>>,
          TError,
          Awaited<ReturnType<typeof getCategories>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCategoriesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getCategories>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить все категории
 */

export function useGetCategoriesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getCategories>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCategoriesInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCategoriesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCategories>>> = ({ signal }) =>
    getCategories(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getCategories>>>;
export type GetCategoriesQueryError = unknown;

export function useGetCategories<
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategories>>,
          TError,
          Awaited<ReturnType<typeof getCategories>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCategories<
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategories>>,
          TError,
          Awaited<ReturnType<typeof getCategories>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCategories<
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить все категории
 */

export function useGetCategories<
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCategoriesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetCategoriesSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCategoriesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCategories>>> = ({ signal }) =>
    getCategories(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCategoriesSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCategories>>
>;
export type GetCategoriesSuspenseQueryError = unknown;

export function useGetCategoriesSuspense<
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCategoriesSuspense<
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCategoriesSuspense<
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить все категории
 */

export function useGetCategoriesSuspense<
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCategoriesSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
