/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */
import { customAxios } from '../../axiosInstance';

import type {
  CategoryResponse,
  CreateSubscriptionRequest,
  CustomSubscriptionRequest,
  GetServicesParams,
  GetSubscriptionsParams,
  PageServiceResponse,
  PageSubscriptionResponse,
  SubscriptionResponse,
  UpdateSubscriptionRequest,
  UploadCustomLogoBody,
} from '../../models';

export const getSubscriptions = () => {
  /**
   * @summary Получить подписку по ID
   */
  const getSubscriptionById = (subscriptionId: string) => {
    return customAxios<SubscriptionResponse>({
      url: `/api/subscription/${subscriptionId}`,
      method: 'GET',
    });
  };
  /**
   * @summary Обновить существующую подписку
   */
  const updateSubscription = (
    subscriptionId: string,
    updateSubscriptionRequest: UpdateSubscriptionRequest,
  ) => {
    return customAxios<SubscriptionResponse>({
      url: `/api/subscription/${subscriptionId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateSubscriptionRequest,
    });
  };
  /**
   * @summary Удалить подписку
   */
  const deleteSubscription = (subscriptionId: string) => {
    return customAxios<void>({ url: `/api/subscription/${subscriptionId}`, method: 'DELETE' });
  };
  /**
   * Возвращает список всех подписок пользователя
   * @summary Получить все подписки пользователя
   */
  const getSubscriptions = (params: GetSubscriptionsParams) => {
    return customAxios<PageSubscriptionResponse>({
      url: `/api/subscription`,
      method: 'GET',
      params,
    });
  };
  /**
   * @summary Создать подписку на существующий сервис
   */
  const createSubscription = (createSubscriptionRequest: CreateSubscriptionRequest) => {
    return customAxios<SubscriptionResponse>({
      url: `/api/subscription`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSubscriptionRequest,
    });
  };
  /**
   * Создаёт новый сервис и подписку. Для загрузки лого используй POST /custom/{subscriptionId}/logo
   * @summary Создать кастомную подписку
   */
  const createCustomSubscription = (customSubscriptionRequest: CustomSubscriptionRequest) => {
    return customAxios<SubscriptionResponse>({
      url: `/api/subscription/custom`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: customSubscriptionRequest,
    });
  };
  /**
   * @summary Загрузить логотип кастомной подписки
   */
  const uploadCustomLogo = (subscriptionId: string, uploadCustomLogoBody: UploadCustomLogoBody) => {
    const formData = new FormData();
    formData.append(`logo`, uploadCustomLogoBody.logo);

    return customAxios<SubscriptionResponse>({
      url: `/api/subscription/custom/${subscriptionId}/logo`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    });
  };
  /**
   * Возвращает список сервисов с пагинацией, фильтром по категории и поиском по имени
   * @summary Поиск сервисов
   */
  const getServices = (params: GetServicesParams) => {
    return customAxios<PageServiceResponse>({
      url: `/api/subscription/service`,
      method: 'GET',
      params,
    });
  };
  /**
   * Возвращает список категорий, чтобы выбрать одну из для подписки
   * @summary Получить все категории
   */
  const getCategories = () => {
    return customAxios<CategoryResponse[]>({ url: `/api/subscription/category`, method: 'GET' });
  };
  return {
    getSubscriptionById,
    updateSubscription,
    deleteSubscription,
    getSubscriptions,
    createSubscription,
    createCustomSubscription,
    uploadCustomLogo,
    getServices,
    getCategories,
  };
};
export type GetSubscriptionByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSubscriptions>['getSubscriptionById']>>
>;
export type UpdateSubscriptionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSubscriptions>['updateSubscription']>>
>;
export type DeleteSubscriptionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSubscriptions>['deleteSubscription']>>
>;
export type GetSubscriptionsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSubscriptions>['getSubscriptions']>>
>;
export type CreateSubscriptionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSubscriptions>['createSubscription']>>
>;
export type CreateCustomSubscriptionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSubscriptions>['createCustomSubscription']>>
>;
export type UploadCustomLogoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSubscriptions>['uploadCustomLogo']>>
>;
export type GetServicesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSubscriptions>['getServices']>>
>;
export type GetCategoriesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSubscriptions>['getCategories']>>
>;
