/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * User Service API
 * User Service API
 * OpenAPI spec version: 1.0
 */
import { useInfiniteQuery, useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type { CurrencyRequest, ProfileResponse } from '../../models';

import { customAxios } from '../../axiosInstance';

/**
 * Изменить валюту в настройках профиля текущего пользователя
 * @summary Изменить валюту
 */
export const changeCurrency = (currencyRequest: CurrencyRequest, signal?: AbortSignal) => {
  return customAxios<void>({
    url: `/api/users/me/currency`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: currencyRequest,
    signal,
  });
};

export const getChangeCurrencyMutationOptions = <
  TError = void | void | void | void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changeCurrency>>,
    TError,
    { data: CurrencyRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof changeCurrency>>,
  TError,
  { data: CurrencyRequest },
  TContext
> => {
  const mutationKey = ['changeCurrency'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof changeCurrency>>,
    { data: CurrencyRequest }
  > = (props) => {
    const { data } = props ?? {};

    return changeCurrency(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChangeCurrencyMutationResult = NonNullable<Awaited<ReturnType<typeof changeCurrency>>>;
export type ChangeCurrencyMutationBody = CurrencyRequest;
export type ChangeCurrencyMutationError = void | void | void | void;

/**
 * @summary Изменить валюту
 */
export const useChangeCurrency = <TError = void | void | void | void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof changeCurrency>>,
      TError,
      { data: CurrencyRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof changeCurrency>>,
  TError,
  { data: CurrencyRequest },
  TContext
> => {
  const mutationOptions = getChangeCurrencyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Получить профиль текущего пользователя
 * @summary Получить профиль
 */
export const getCurrentUserProfile = (signal?: AbortSignal) => {
  return customAxios<ProfileResponse>({ url: `/api/users/me`, method: 'GET', signal });
};

export const getGetCurrentUserProfileInfiniteQueryKey = () => {
  return ['infinate', `/api/users/me`] as const;
};

export const getGetCurrentUserProfileQueryKey = () => {
  return [`/api/users/me`] as const;
};

export const getGetCurrentUserProfileInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getCurrentUserProfile>>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentUserProfileInfiniteQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUserProfile>>> = ({ signal }) =>
    getCurrentUserProfile(signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getCurrentUserProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentUserProfileInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUserProfile>>
>;
export type GetCurrentUserProfileInfiniteQueryError =
  | ProfileResponse
  | ProfileResponse
  | ProfileResponse
  | ProfileResponse;

export function useGetCurrentUserProfileInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getCurrentUserProfile>>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserProfile>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserProfile>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCurrentUserProfileInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getCurrentUserProfile>>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserProfile>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserProfile>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCurrentUserProfileInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getCurrentUserProfile>>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить профиль
 */

export function useGetCurrentUserProfileInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getCurrentUserProfile>>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCurrentUserProfileInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetCurrentUserProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUserProfile>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentUserProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUserProfile>>> = ({ signal }) =>
    getCurrentUserProfile(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUserProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentUserProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUserProfile>>
>;
export type GetCurrentUserProfileQueryError =
  | ProfileResponse
  | ProfileResponse
  | ProfileResponse
  | ProfileResponse;

export function useGetCurrentUserProfile<
  TData = Awaited<ReturnType<typeof getCurrentUserProfile>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserProfile>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserProfile>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCurrentUserProfile<
  TData = Awaited<ReturnType<typeof getCurrentUserProfile>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserProfile>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserProfile>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCurrentUserProfile<
  TData = Awaited<ReturnType<typeof getCurrentUserProfile>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить профиль
 */

export function useGetCurrentUserProfile<
  TData = Awaited<ReturnType<typeof getCurrentUserProfile>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCurrentUserProfileQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetCurrentUserProfileSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUserProfile>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentUserProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUserProfile>>> = ({ signal }) =>
    getCurrentUserProfile(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUserProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentUserProfileSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUserProfile>>
>;
export type GetCurrentUserProfileSuspenseQueryError =
  | ProfileResponse
  | ProfileResponse
  | ProfileResponse
  | ProfileResponse;

export function useGetCurrentUserProfileSuspense<
  TData = Awaited<ReturnType<typeof getCurrentUserProfile>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCurrentUserProfileSuspense<
  TData = Awaited<ReturnType<typeof getCurrentUserProfile>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetCurrentUserProfileSuspense<
  TData = Awaited<ReturnType<typeof getCurrentUserProfile>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить профиль
 */

export function useGetCurrentUserProfileSuspense<
  TData = Awaited<ReturnType<typeof getCurrentUserProfile>>,
  TError = ProfileResponse | ProfileResponse | ProfileResponse | ProfileResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getCurrentUserProfile>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCurrentUserProfileSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
