/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * User Service API
 * User Service API
 * OpenAPI spec version: 1.0
 */
import type { CurrencyRequest, ProfileResponse } from '../../models';

import { customAxios } from '../../axiosInstance';

export const getUser = () => {
  /**
   * Изменить валюту в настройках профиля текущего пользователя
   * @summary Изменить валюту
   */
  const changeCurrency = (currencyRequest: CurrencyRequest) => {
    return customAxios<void>({
      url: `/api/users/me/currency`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: currencyRequest,
    });
  };
  /**
   * Получить профиль текущего пользователя
   * @summary Получить профиль
   */
  const getCurrentUserProfile = () => {
    return customAxios<ProfileResponse>({ url: `/api/users/me`, method: 'GET' });
  };
  return { changeCurrency, getCurrentUserProfile };
};
export type ChangeCurrencyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUser>['changeCurrency']>>
>;
export type GetCurrentUserProfileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUser>['getCurrentUserProfile']>>
>;
