/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * User Service API
 * User Service API
 * OpenAPI spec version: 1.0
 */
import type {
  AuthResponse,
  RefreshTokenRequest,
  UserLoginRequest,
  UserRegistrationRequest,
} from '../../models';

import { customAxios } from '../../axiosInstance';

export const getSecurity = () => {
  /**
   * Пользователь регистрируется с данными из тела запроса
   * @summary Регистрация пользователя
   */
  const register = (userRegistrationRequest: UserRegistrationRequest) => {
    return customAxios<AuthResponse>({
      url: `/api/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userRegistrationRequest,
    });
  };
  /**
   * Обновляем Access token с помощью Refresh token
   * @summary Обновление токена
   */
  const refreshToken = (refreshTokenRequest: RefreshTokenRequest) => {
    return customAxios<AuthResponse | AuthResponse>({
      url: `/api/auth/refresh-token`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: refreshTokenRequest,
    });
  };
  /**
   * Выход пользователя из системы
   * @summary Выход пользователя
   */
  const logout = () => {
    return customAxios<void>({ url: `/api/auth/logout`, method: 'POST' });
  };
  /**
   * Пользователь аутентифицируется по данным из тела запроса
   * @summary Вход пользователя
   */
  const login = (userLoginRequest: UserLoginRequest) => {
    return customAxios<AuthResponse>({
      url: `/api/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userLoginRequest,
    });
  };
  return { register, refreshToken, logout, login };
};
export type RegisterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSecurity>['register']>>
>;
export type RefreshTokenResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSecurity>['refreshToken']>>
>;
export type LogoutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSecurity>['logout']>>
>;
export type LoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSecurity>['login']>>>;
