/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */

/**
 * Стандартная структура сообщения об ошибке
 */
export interface BaseExceptionMessage {
  /** Время возникновения ошибки */
  timestamp?: string;
  /** Тип ошибки */
  error?: string;
  /** Статус ответа */
  status?: number;
  /** Описание ошибки */
  message?: string;
}
