/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */

/**
 * DTO представляющий данные о категории
 */
export interface CategoryResponse {
  /** Уникальный идентификатор категории */
  categoryId?: number;
  /** Название категории */
  name?: string;
}
