/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Analytics Service API
 * Analytics Service API
 * OpenAPI spec version: 1.0
 */

/**
 * Категория подписок
 */
export type CategoryAnalyticsResponseCategory =
  (typeof CategoryAnalyticsResponseCategory)[keyof typeof CategoryAnalyticsResponseCategory];

export const CategoryAnalyticsResponseCategory = {
  STREAMING_VIDEO: 'STREAMING_VIDEO',
  STREAMING_MUSIC: 'STREAMING_MUSIC',
  CLOUD_STORAGE: 'CLOUD_STORAGE',
  PRODUCTIVITY: 'PRODUCTIVITY',
  GAMING: 'GAMING',
  NEWS: 'NEWS',
  EDUCATION: 'EDUCATION',
  SOCIAL_MEDIA: 'SOCIAL_MEDIA',
  SHOPPING: 'SHOPPING',
  HEALTH_FITNESS: 'HEALTH_FITNESS',
  FINANCE: 'FINANCE',
  TRAVEL: 'TRAVEL',
} as const;
