/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */

/**
 * Данные для создания подписки
 */
export interface CreateSubscriptionRequest {
  /** Идентификатор сервиса */
  serviceId: string;
  /** Цена подписки */
  amount: number;
  /** Время платы по подписке */
  timeToPay: string;
}
