/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * User Service API
 * User Service API
 * OpenAPI spec version: 1.0
 */
import type { CurrencyRequestCurrency } from './currencyRequestCurrency';

/**
 * DTO для обновления валюты пользователя
 */
export interface CurrencyRequest {
  /** Валюта */
  currency?: CurrencyRequestCurrency;
}
