/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * User Service API
 * User Service API
 * OpenAPI spec version: 1.0
 */

/**
 * Валюта
 */
export type CurrencyRequestCurrency =
  (typeof CurrencyRequestCurrency)[keyof typeof CurrencyRequestCurrency];

export const CurrencyRequestCurrency = {
  RUB: 'RUB',
  USD: 'USD',
  EUR: 'EUR',
} as const;
