/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */

/**
 * DTO для создания кастомной подписки
 */
export interface CustomSubscriptionRequest {
  /**
   * Название сервиса подписки
   * @minLength 1
   */
  serviceName: string;
  /** Уникальный идентификатор категории */
  categoryId: number;
  /** Цена подписки */
  amount: number;
  /** Время платы по подписке */
  timeToPay: string;
}
