/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */
import type { Pageable } from './pageable';

export type GetServicesParams = {
  categoryId?: number;
  search?: string;
  /**
   * Если true — вернуть только дефолтные сервисы, если false — только кастомные, если не задано — все
   */
  isDefault?: boolean;
  pageable: Pageable;
};
