/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */
import type { Pageable } from './pageable';

export type GetSubscriptionsParams = {
  categoryId?: number;
  pageable: Pageable;
};
