/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * User Service API
 * User Service API
 * OpenAPI spec version: 1.0
 */

/**
 * Текущие настройки напоминаний об оплате подписок пользователя
 */
export interface NotificationSettingsResponse {
  /** Уведомлять за 1 день до списания */
  notify1Day?: boolean;
  /** Уведомлять за 3 дня до списания */
  notify3Days?: boolean;
  /** Уведомлять за 7 дней до списания */
  notify7Days?: boolean;
}
