/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */
import type { PageableObject } from './pageableObject';
import type { SortObject } from './sortObject';
import type { SubscriptionResponse } from './subscriptionResponse';

export interface PageSubscriptionResponse {
  totalPages?: number;
  totalElements?: number;
  pageable?: PageableObject;
  numberOfElements?: number;
  size?: number;
  content?: SubscriptionResponse[];
  number?: number;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  empty?: boolean;
}
