/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */
import type { PageableObject } from './pageableObject';
import type { ServiceResponse } from './serviceResponse';
import type { SortObject } from './sortObject';

export interface PageServiceResponse {
  totalPages?: number;
  totalElements?: number;
  pageable?: PageableObject;
  numberOfElements?: number;
  size?: number;
  content?: ServiceResponse[];
  number?: number;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  empty?: boolean;
}
