/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */
import type { SortObject } from './sortObject';

export interface PageableObject {
  pageNumber?: number;
  paged?: boolean;
  pageSize?: number;
  unpaged?: boolean;
  offset?: number;
  sort?: SortObject;
}
