/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * User Service API
 * User Service API
 * OpenAPI spec version: 1.0
 */

export type ProfileResponseCurrency =
  (typeof ProfileResponseCurrency)[keyof typeof ProfileResponseCurrency];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileResponseCurrency = {
  RUB: 'RUB',
  USD: 'USD',
  EUR: 'EUR',
} as const;
