/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * User Service API
 * User Service API
 * OpenAPI spec version: 1.0
 */

/**
 * DTO для обновления JWT токенов
 */
export interface RefreshTokenRequest {
  /**
   * Refresh token пользователя с помощью которого обновляется Access token
   * @minLength 1
   */
  refreshToken: string;
}
