/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */
import type { ServiceResponseCategory } from './serviceResponseCategory';

/**
 * DTO представляющий данные сервиса
 */
export interface ServiceResponse {
  /** Уникальный идентификатор сервиса UUID */
  serviceId?: string;
  /** Название сервиса */
  serviceName?: string;
  /** Ссылка на лого сервиса */
  logoUrl?: string;
  /** Категория сервиса */
  category?: ServiceResponseCategory;
  /** Является ли сервис дефолтным (true) или кастомным пользовательским (false) */
  isDefault?: boolean;
}
