/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */

/**
 * Категория сервиса
 */
export type ServiceResponseCategory =
  (typeof ServiceResponseCategory)[keyof typeof ServiceResponseCategory];

export const ServiceResponseCategory = {
  STREAMING_VIDEO: 'STREAMING_VIDEO',
  STREAMING_MUSIC: 'STREAMING_MUSIC',
  CLOUD_STORAGE: 'CLOUD_STORAGE',
  PRODUCTIVITY: 'PRODUCTIVITY',
  GAMING: 'GAMING',
  NEWS: 'NEWS',
  EDUCATION: 'EDUCATION',
  SOCIAL_MEDIA: 'SOCIAL_MEDIA',
  SHOPPING: 'SHOPPING',
  HEALTH_FITNESS: 'HEALTH_FITNESS',
  FINANCE: 'FINANCE',
  TRAVEL: 'TRAVEL',
} as const;
