/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionResponseCategory } from './subscriptionResponseCategory';

/**
 * DTO представляющий все данные подписки
 */
export interface SubscriptionResponse {
  /** Уникальный идентификатор подписки UUID */
  subscriptionId?: string;
  /** Название сервиса подписки */
  serviceName?: string;
  /** Цена подписки */
  amount?: number;
  /** Время платы по подписке */
  timeToPay?: string;
  /** Флаг ежемесячной подписки. true — подписка автоматически продлевается каждый месяц, false — подписка будет удалена в день списания */
  isMonth?: boolean;
  /** Ссылка на лого подписки, по которой можно получить фото из облачного хранилища */
  logoUrl?: string;
  /** Категория сервиса */
  category?: SubscriptionResponseCategory;
  /** Способ оплаты подписки */
  paymentMethod?: string;
}
