/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Analytics Service API
 * Analytics Service API
 * OpenAPI spec version: 1.0
 */

/**
 * Суммы списаний в ближайшие периоды
 */
export interface UpcomingChargesResponse {
  /** Сумма списаний в ближайшие 7 дней */
  nextWeek?: number;
  /** Сумма списаний в ближайшие 30 дней */
  nextMonth?: number;
  /** Количество активных подписок */
  activeSubscriptionsCount?: number;
  /** Количество подписок к оплате на этой неделе */
  subscriptionsToPayThisWeekCount?: number;
  /** Количество подписок к оплате в этом месяце */
  subscriptionsToPayThisMonthCount?: number;
  /** Сумма оплат по подпискам за этот месяц */
  totalAmountToPayThisMonth?: number;
}
