/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Subscription Service API
 * Subscription Service API
 * OpenAPI spec version: 1.0
 */

/**
 * Данные для обновления подписки
 */
export interface UpdateSubscriptionRequest {
  /** Цена подписки */
  amount: number;
  /** Флаг ежемесячной подписки. true — подписка автоматически продлевается каждый месяц, false — подписка будет удалена в день списания */
  isMonth: boolean;
  /** Время платы по подписке */
  timeToPay: string;
  /** Способ оплаты подписки */
  paymentMethod?: string;
}
