/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * User Service API
 * User Service API
 * OpenAPI spec version: 1.0
 */

/**
 * DTO для входа пользователя
 */
export interface UserLoginRequest {
  /**
   * Электронная почта пользователя
   * @minLength 1
   */
  email: string;
  /**
   * Пароль пользователя
   * @minLength 1
   */
  password: string;
}
