/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * User Service API
 * User Service API
 * OpenAPI spec version: 1.0
 */

/**
 * DTO для регистрации пользователя
 */
export interface UserRegistrationRequest {
  /**
   * Username пользователя. Username должен содержать только символы a-z, 0-9 и _
   * @minLength 1
   */
  username: string;
  /**
   * Электронная почта пользователя
   * @minLength 1
   */
  email: string;
  /** Пароль пользователя. Он должен содержать не менее 8 символов, не менее 1 заглавной буквы и не менее 1 цифры. Пароль не должен содержать пробелов. */
  password: string;
}
